### ISSUE TITLE
[feat] Criar controller de users

### ISSUE THREAD

**Issue by lucasbraide** [ceos-jr/Atlas#101]
# **Descrição**
Criar controllers para as funções de CRUD de usuário

- CreateUser - ok
- ReadUser
- UpdateUser - ok
- DeleteUser - ok

Com base no padrão definido dos controllers existentes.

Os controllers devem ser implementados em `backend/controllers/user`

# **O que é um controller?**

Para criar um novo user, o controller recebe e valida os dados da solicitação, chama o serviço para validar as entradas correspondente e retorna a resposta ao cliente de acordo com o sucesso ou erro da solicitação.

**Comment by ArtroxGabriel** [comment]
@ArtroxGabriel Criar issue para service do user

**Comment by ArtroxGabriel** [comment]
Completar issue para prosseguir no controller:
- [ ] #174
